query CosplayCon {
  cosplayCon {
    eventInfo {
      id
      startDate
      endDate
      vipStartDate
      vipEndDate
      location
      showButton
      price
      vipPrice
      buttonLabel
      buttonUrl
    }
    seo {
      metaTitle
      metaDescription
      shareImage {
        name
        width
        height
        alternativeText
      }
    }
    sections {
      title
      subText
      text
      Images {
        name
        alternativeText
        url
        width
        height
        caption
      }
      table
    }
  }
}
